In [ ]:
import numpy as np

a = np.array([1,3,5,7,9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [3]:
a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])

#陣列的運算
a + b 

array([ 3,  7, 11, 15, 19])

In [4]:
#2維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [7]:
np.random.rand()
np.random.rand(4, 4)

array([[0.95842165, 0.58016019, 0.31628632, 0.22203474],
       [0.18491967, 0.06278622, 0.44716065, 0.87478738],
       [0.15575188, 0.81582393, 0.60042482, 0.43264496],
       [0.67825103, 0.95849185, 0.92182525, 0.8264863 ]])

In [15]:
np.random.randint(50,101,size=(10,5))

array([[ 85,  56,  96,  67,  63],
       [ 63,  67,  87,  94,  98],
       [ 84,  68,  87,  85,  53],
       [ 55,  89,  73,  69,  83],
       [ 60,  62,  80,  98,  76],
       [ 50,  69,  78,  65,  98],
       [ 97,  88, 100,  69,  93],
       [ 94,  71,  80,  57,  79],
       [ 86,  92,  62,  52,  85],
       [ 51,  83,  94,  91,  71]], dtype=int32)