In [3]:
import numpy as np
arr = np.arange(10)*10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#索引
arr[1]

#slice
arr[:5] #挑選前5個
arr[-5:] #挑選最後5個

array([50, 60, 70, 80, 90])

In [6]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 65,  81,  94,  93,  77],
       [ 74,  77,  95,  51,  98],
       [ 59,  59,  82,  66,  82],
       [ 94,  84,  79,  95,  90],
       [ 54,  57,  74,  68,  75],
       [ 69,  95,  83,  56,  74],
       [ 59,  87,  76,  83,  71],
       [ 68,  92,  77,  69,  96],
       [ 80,  69,  96,  81,  50],
       [ 59,  50,  59,  96,  59],
       [ 58,  63,  85,  85,  72],
       [ 68,  54,  85,  77,  88],
       [ 96,  84,  58,  67,  91],
       [ 71,  72,  57,  93,  67],
       [ 78,  66,  51,  64,  91],
       [ 58,  55,  51,  55,  67],
       [ 52,  80,  84,  99,  82],
       [ 95,  91,  97,  79,  70],
       [ 55,  87,  55,  57,  93],
       [ 86,  68,  98,  74,  87],
       [ 88,  57,  63,  96,  70],
       [ 94,  65,  77,  90,  89],
       [ 80,  62,  57,  68,  74],
       [ 52,  77, 100,  53,  70],
       [ 53,  60,  71,  88,  75],
       [ 51,  56,  99,  52,  85],
       [ 78,  79,  93, 100,  99],
       [ 88,  88,  76,  68,  81],
       [ 53,  67,  67,  51,  50],
       [ 55,  

In [8]:
#第一位學生的分數
#不同的寫法
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[65, 81, 94, 93, 77]], dtype=int32)

In [9]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[65, 81, 94],
       [74, 77, 95],
       [59, 59, 82],
       [94, 84, 79],
       [54, 57, 74]], dtype=int32)

In [10]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([ 94,  95,  82,  79,  74,  83,  76,  77,  96,  59,  85,  85,  58,
        57,  51,  51,  84,  97,  55,  98,  63,  77,  57, 100,  71,  99,
        93,  76,  67,  79, 100,  95,  55,  90,  70,  64,  86,  68,  91,
        69,  58,  83,  94,  92,  69,  97,  74,  67,  57,  95], dtype=int32)

In [11]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([410, 395, 348, 442, 328, 377, 376, 402, 376, 323, 363, 372, 396,
       360, 350, 286, 397, 432, 347, 413, 374, 415, 341, 352, 347, 343,
       449, 401, 288, 368, 385, 408, 358, 397, 383, 393, 391, 334, 373,
       363, 317, 397, 381, 391, 394, 401, 345, 358, 347, 423], dtype=int32)

In [12]:
total / 5

array([82. , 79. , 69.6, 88.4, 65.6, 75.4, 75.2, 80.4, 75.2, 64.6, 72.6,
       74.4, 79.2, 72. , 70. , 57.2, 79.4, 86.4, 69.4, 82.6, 74.8, 83. ,
       68.2, 70.4, 69.4, 68.6, 89.8, 80.2, 57.6, 73.6, 77. , 81.6, 71.6,
       79.4, 76.6, 78.6, 78.2, 66.8, 74.6, 72.6, 63.4, 79.4, 76.2, 78.2,
       78.8, 80.2, 69. , 71.6, 69.4, 84.6])

In [13]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([82. , 79. , 69.6, 88.4, 65.6, 75.4, 75.2, 80.4, 75.2, 64.6, 72.6,
       74.4, 79.2, 72. , 70. , 57.2, 79.4, 86.4, 69.4, 82.6, 74.8, 83. ,
       68.2, 70.4, 69.4, 68.6, 89.8, 80.2, 57.6, 73.6, 77. , 81.6, 71.6,
       79.4, 76.6, 78.6, 78.2, 66.8, 74.6, 72.6, 63.4, 79.4, 76.2, 78.2,
       78.8, 80.2, 69. , 71.6, 69.4, 84.6])

In [14]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([82. , 79. , 69.6, 88.4, 65.6, 75.4, 75.2, 80.4, 75.2, 64.6, 72.6,
       74.4, 79.2, 72. , 70. , 57.2, 79.4, 86.4, 69.4, 82.6, 74.8, 83. ,
       68.2, 70.4, 69.4, 68.6, 89.8, 80.2, 57.6, 73.6, 77. , 81.6, 71.6,
       79.4, 76.6, 78.6, 78.2, 66.8, 74.6, 72.6, 63.4, 79.4, 76.2, 78.2,
       78.8, 80.2, 69. , 71.6, 69.4, 84.6])